-- MySQL Script generated by MySQL Workbench
-- 04/23/15 23:59:58
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nepum_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nepum_db` ;
CREATE SCHEMA IF NOT EXISTS `nepum_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `nepum_db` ;

-- -----------------------------------------------------
-- Table `Dominios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dominios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Dominios` (
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Instituicoes de Saude_idEntidades de Saude` INT NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Bloco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bloco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Bloco` (
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Dominios_Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Instituicoes de Saude`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Instituicoes de Saude` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Instituicoes de Saude` (
  `Codigo de Entidade` INT NOT NULL,
  `Nome Entidade` VARCHAR(45) NULL,
  `Bloco_Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo de Entidade`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Lingua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lingua` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Lingua` (
  `nome` VARCHAR(45) NULL,
  `sigla` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`sigla`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Objetivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Objetivo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Objetivo` (
  `Objetivo` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`Objetivo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Estrutura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estrutura` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Estrutura` (
  `codigo` INT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Língua_sigla` VARCHAR(4) NOT NULL,
  `Objetivo_Objetivo` VARCHAR(12) NOT NULL,
  `numero exercicios` INT NULL,
  `numero minimo de questoes` INT NULL,
  `questoes por exercicio` INT NULL,
  `numero minimo de respostas` INT NULL,
  `respostas por exercicio` INT NULL,
  PRIMARY KEY (`Titulo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Exercicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Exercicio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Exercicio` (
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `Domínios_Nome` VARCHAR(45) NOT NULL,
  `Estrutura_Título` VARCHAR(45) NOT NULL,
  `Bloco_Nome` VARCHAR(45) NOT NULL,
  `tarefa` VARCHAR(45) NULL,
  `Nivel_nivel` VARCHAR(45) NOT NULL,
  `tempo padrao` DATETIME NULL,
  `ficheiro fala` VARCHAR(45) NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Patologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Patologia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Patologia` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Relatorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Relatorio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Relatorio` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `resultado` VARCHAR(45) NULL,
  `sessoes concluidas` INT NULL,
  `sessoes a realizar` INT NOT NULL,
  `Instituicoes de Saude_Codigo de Entidade` INT NOT NULL,
  `Patologias` VARCHAR(45) NULL,
  `data de inicio` DATE NULL,
  `data de fim` DATE NULL,
  `Exercicio_nome` INT NOT NULL,
  `tempo total` DATETIME NULL,
  `tempo medio` VARCHAR(45) NULL,
  `Patologia_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Utilizador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Utilizador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Utilizador` (
  `login` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NULL,
  `Morada` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Contacto` VARCHAR(45) NULL,
  `Patologias` VARCHAR(45) NULL,
  `Código` VARCHAR(45) NULL,
  `data nascimento` VARCHAR(45) NULL,
  `Relatorio_codigo` INT NULL,
  `Tipo utilizador_Código` INT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Som`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Som` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Som` (
  `duracao` VARCHAR(8) NULL,
  `nome` VARCHAR(45) NOT NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Video` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Video` (
  `nome` VARCHAR(45) NOT NULL,
  `duracao` INT NULL,
  `altura` VARCHAR(45) NULL,
  `largura` VARCHAR(45) NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Imagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Imagem` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Imagem` (
  `nome` VARCHAR(45) NOT NULL,
  `largura` INT NULL,
  `altura` INT NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Multimedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Multimedia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Multimedia` (
  `Codigo` INT NOT NULL,
  `Título` VARCHAR(45) NULL,
  `Descricao` VARCHAR(500) NULL,
  `Ficheiro fala (auxilio descricao)` VARCHAR(45) NULL,
  `Som_duracao` VARCHAR(8) NULL,
  `Video_nome` VARCHAR(45) NULL,
  `Texto_campo de texto` VARCHAR(300) NULL,
  `Imagem_nome` VARCHAR(45) NULL,
  `Lingua_sigla` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Resposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Resposta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Resposta` (
  `Resposta` VARCHAR(45) NOT NULL,
  `Exercício_nome` INT NOT NULL,
  PRIMARY KEY (`Resposta`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Questao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Questao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Questao` (
  `questao` VARCHAR(45) NOT NULL,
  `Exercício_nome` INT NOT NULL,
  `Resposta_Resposta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`questao`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Utilizador`
-- -----------------------------------------------------
START TRANSACTION;
USE `nepum_db`;
INSERT INTO `Utilizador` (`login`, `pass`, `Morada`, `Nome`, `Contacto`, `Patologias`, `Código`, `data nascimento`, `Relatorio_codigo`, `Tipo utilizador_Código`) VALUES ('admin', 'admin', 'Rua', NULL, NULL, NULL, '1', NULL, NULL, NULL);

COMMIT;

